spring:
  application:
    name: ConsumerUserFeign
server:
  port: 7001
eureka:
  client:
    service-url:
      defaultZone:
        http://localhost:9000/eureka/
feign:
  hystrix:
    enabled: true
